import fs from 'fs'
import os from 'os'
import path from 'path'
import crypto from 'crypto'
import SettingsManager from '../services/main/settingsManager.js'
import { BackupManager } from '../services/backup/backupManager.js'
import { failureMessage, hashRestorePhrase, RestoreManager } from '../services/backup/restoreManager.js'
import { decodeIndexesRow, decryptTableRows, decryptTableShard, encodeIndexesRow, encryptTableRows } from '../services/backup/segments.js'
import { encodeTLV, integerToUint8Array } from '../services/helpers/tlv.js'
import { scbFromSnapshot } from '../services/main/unlocker.js'
import { Unlocker } from '../services/main/unlocker.js'
import { BACKUP_TABLE_IDS, backupTableFilename, backupTableStagingFilename, selectConsistentSnapshot, type BackupTableId } from '../services/backup/backupTables.js'
import { atomicWriteFile } from '../services/backup/atomicWrite.js'
import { deriveBackupKeys } from '../services/backup/derivation.js'
import Storage, { GetTestStorageSettings } from '../services/storage/index.js'
import { Utils } from '../services/helpers/utilsWrapper.js'
import { NostrSender } from '../services/nostr/sender.js'
import { AdminManager } from '../services/main/adminManager.js'
import { Swaps } from '../services/lnd/swaps/swaps.js'
import { EnrollManager } from '../services/CLINK/enrollManager.js'
import { CLINK_ENROLL_KIND, CLINK_VERSION } from '../services/CLINK/clinkConstants.js'
import { toClinkCtx } from '../services/CLINK/clinkTypes.js'
import * as WizardTypes from '../../proto/wizard_service/autogenerated/ts/types.js'
import * as Types from '../../proto/autogenerated/ts/types.js'
import { StorageTestBase } from './testBase.js'
import { pickDefaultApp } from '../services/main/adminNodeSettings.js'

export const ignore = false
export const dev = false
export const requires = 'storage' as const

const TEST_PHRASE = 'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about'
const TEST_SEED = TEST_PHRASE.split(' ')
const OTHER_PHRASE = 'legal winner thank year wave sausage worth useful legal winner thank yellow'
const TEST_WALLET_PUB = 'restore-wallet-a'
const OTHER_WALLET_PUB = 'restore-wallet-b'

type SpyBackup = BackupManager & { notified: BackupTableId[], fullUploads: number }

const makeSpyBackup = (): SpyBackup => {
    const notified: BackupTableId[] = []
    const spy = {
        notified,
        fullUploads: 0,
        notifyBackupTable: async (...ids: BackupTableId[]) => {
            notified.push(...ids)
        },
        uploadAllTables: async () => {
            spy.fullUploads++
        },
    }
    return spy as unknown as SpyBackup
}

const tempBackupDir = () => fs.mkdtempSync(path.join(os.tmpdir(), 'pub-backup-'))

const withTimeout = async <T>(p: Promise<T>, ms: number, msg: string): Promise<T> => {
    let t: ReturnType<typeof setTimeout> | undefined
    try {
        return await Promise.race([
            p,
            new Promise<never>((_, reject) => {
                t = setTimeout(() => reject(new Error(msg)), ms)
            }),
        ])
    } finally {
        if (t) clearTimeout(t)
    }
}

const listEncFiles = (dir: string) =>
    fs.existsSync(dir) ? fs.readdirSync(dir).filter(f => f.endsWith('.enc')).sort() : []

const openSecondStorage = async () => {
    const settings = GetTestStorageSettings()
    const utils = new Utils({ dataDir: settings.dataDir, allowResetMetricsStorages: true }, new NostrSender())
    const storage = new Storage(settings, utils)
    await storage.Connect(console.log)
    return storage
}

const markDbImported = async (storage: Storage) => {
    await storage.applicationStorage.AddApplication('imported', true)
}

const sortBy = <T>(rows: T[], key: (r: T) => string) =>
    [...rows].sort((a, b) => key(a).localeCompare(key(b)))

export default async (T: StorageTestBase) => {
    await testGateNoDestination(T)
    await testGateNoSeed(T)
    await testUploadAllTablesWritesEveryShard(T)
    await testUploadAllTablesWithoutSnapshotsOmitsIndexes(T)
    await testAtomicLocalReplace(T)
    await testSnapshotPicksCompleteStagingGeneration(T)
    await testSnapshotIgnoresIncompleteNewGeneration(T)
    await testSnapshotRejectsMixedGenerations(T)
    await testRefusesWhenLndStarted(T)
    await testResumeAfterDbCommitted(T)
    await testResumePhraseMismatch(T)
    await testResumeWithoutWalletRefused(T)
    await testResumeCleanDbRefused(T)
    await testResumeMissingPhraseRefused(T)
    await testResumeLndActiveWithoutWalletPub(T)
    await testResumeWalletMismatch(T)
    await testWrongPhraseLeavesNoCheckpoint(T)
    await testScbFailureKeepsCheckpoint(T)
    await testScbRetryCompletes(T)
    await testCompletedDoesNotHangStartupWaiter(T)
    await testHasOngoingRecovery(T)
    await testConcurrentRestoreRejected(T)
    await testLocalRoundtrip(T)
    await testMissingShardFailsClosed(T)
    await testEmptyProductsShardImports(T)
    await testIndexesWithoutAddressUpdate(T)
    await testIndexesZeroSnapshot(T)
    await testEmptyIndexesShardFails(T)
    await testIndexesUnknownDoesNotClobber(T)
    await testChannelStateUnknownDoesNotClobber(T)
    testIndexesScbRoundtrip(T)
    await testNoChannelsSkipsScbRestore(T)
    await testShardWithoutScbFieldFails(T)
    testScbFromSnapshot(T)
    await testHookLspThreshold(T)
    await testHookRemoteBackupEnable(T)
    await testHookDefaultAppRename(T)
    await testHookEnrollCreate(T)
}

const testRefusesWhenLndStarted = async (T: StorageTestBase) => {
    T.d('starting testRefusesWhenLndStarted')
    const dest = await openSecondStorage()
    const dataDir = dest.getStorageSettings().dataDir
    try {
        const settings = new SettingsManager(dest)
        await settings.InitSettings()
        let movedOn = false
        const unlocker = {
            WalletExists: async () => true,
            Restore: async () => { movedOn = true; return { adminMacaroon: '' } },
            PostRestore: async () => { movedOn = true },
            ApplyScb: async () => { movedOn = true },
        } as unknown as Unlocker
        const restore = new RestoreManager(dest, settings, unlocker)
        fs.mkdirSync(dataDir, { recursive: true })
        fs.writeFileSync(restore.getCheckpointPath(), 'STARTED')
        const result = await restore.RestoreFromSource({
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: path.join(dataDir, 'missing-backup') },
        })
        T.expect(result.success).to.equal(false)
        T.expect(result.error || '').to.contain('already has a wallet')
        T.expect(result.entries_restored).to.equal(0)
        T.expect(result.scb_restored).to.equal(false)
        T.expect(movedOn).to.equal(false)
        T.expect(await dest.IsDbClean()).to.equal(true)
    } finally {
        dest.Stop()
        fs.rmSync(dataDir, { recursive: true, force: true })
    }
}

const testResumeAfterDbCommitted = async (T: StorageTestBase) => {
    T.d('starting testResumeAfterDbCommitted')
    const dir = tempBackupDir()
    const dest = await openSecondStorage()
    const dataDir = dest.getStorageSettings().dataDir
    try {
        const sourceSettings = new SettingsManager(T.storage)
        await sourceSettings.InitSettings()
        await seedDialtone(T, sourceSettings)
        await writeLocalBackup(T, dir, 4)
        const settings = new SettingsManager(dest)
        await settings.InitSettings()
        await markDbImported(dest)
        let postRestoreCalls = 0
        let restoreCalls = 0
        const applied: Buffer[] = []
        const unlocker = {
            WalletExists: async () => true,
            Restore: async () => { restoreCalls++; return { adminMacaroon: 'mac' } },
            PostRestore: async () => {
                postRestoreCalls++
                return TEST_WALLET_PUB
            },
            ApplyScb: async (scb: Buffer) => { applied.push(scb) },
        } as unknown as Unlocker
        const restore = new RestoreManager(dest, settings, unlocker)
        fs.mkdirSync(dataDir, { recursive: true })
        fs.writeFileSync(restore.getCheckpointPath(), 'DB_COMMITTED')
        fs.writeFileSync(restore.getPhraseHashPath(), hashRestorePhrase(TEST_PHRASE))
        const result = await restore.RestoreFromSource({
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: dir },
        })
        T.expect(result.success).to.equal(true)
        T.expect(result.error || '').to.equal('')
        T.expect(restoreCalls).to.equal(0)
        T.expect(postRestoreCalls).to.equal(1)
        T.expect(applied.length).to.equal(1)
        T.expect(applied[0].equals(SAMPLE_SCB)).to.equal(true)
        T.expect(result.scb_restored).to.equal(true)
        T.expect(fs.readFileSync(restore.getCheckpointPath(), 'utf8')).to.equal('COMPLETED')
        T.expect(fs.existsSync(restore.getPhraseHashPath())).to.equal(false)
        T.expect(fs.existsSync(restore.getWalletPubPath())).to.equal(false)
    } finally {
        dest.Stop()
        fs.rmSync(dataDir, { recursive: true, force: true })
        fs.rmSync(dir, { recursive: true, force: true })
    }
}

const testResumePhraseMismatch = async (T: StorageTestBase) => {
    T.d('starting testResumePhraseMismatch')
    const dest = await openSecondStorage()
    const dataDir = dest.getStorageSettings().dataDir
    try {
        const settings = new SettingsManager(dest)
        await settings.InitSettings()
        await markDbImported(dest)
        let movedOn = false
        const unlocker = {
            WalletExists: async () => true,
            Restore: async () => { movedOn = true; return { adminMacaroon: '' } },
            PostRestore: async () => { movedOn = true },
            ApplyScb: async () => { movedOn = true },
        } as unknown as Unlocker
        const restore = new RestoreManager(dest, settings, unlocker)
        fs.mkdirSync(dataDir, { recursive: true })
        fs.writeFileSync(restore.getCheckpointPath(), 'DB_COMMITTED')
        fs.writeFileSync(restore.getPhraseHashPath(), hashRestorePhrase(TEST_PHRASE))
        const result = await restore.RestoreFromSource({
            phrase: OTHER_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: path.join(dataDir, 'missing-backup') },
        })
        T.expect(result.success).to.equal(false)
        T.expect(result.error || '').to.contain('does not match')
        T.expect(movedOn).to.equal(false)
    } finally {
        dest.Stop()
        fs.rmSync(dataDir, { recursive: true, force: true })
    }
}

const testResumeWithoutWalletRefused = async (T: StorageTestBase) => {
    T.d('starting testResumeWithoutWalletRefused')
    const dest = await openSecondStorage()
    const dataDir = dest.getStorageSettings().dataDir
    try {
        const settings = new SettingsManager(dest)
        await settings.InitSettings()
        let movedOn = false
        const unlocker = {
            WalletExists: async () => false,
            Restore: async () => { movedOn = true; return { adminMacaroon: '' } },
            PostRestore: async () => { movedOn = true },
            ApplyScb: async () => { movedOn = true },
        } as unknown as Unlocker
        const restore = new RestoreManager(dest, settings, unlocker)
        fs.mkdirSync(dataDir, { recursive: true })
        fs.writeFileSync(restore.getCheckpointPath(), 'DB_COMMITTED')
        fs.writeFileSync(restore.getPhraseHashPath(), hashRestorePhrase(TEST_PHRASE))
        const result = await restore.RestoreFromSource({
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: path.join(dataDir, 'missing-backup') },
        })
        T.expect(result.success).to.equal(false)
        T.expect(result.error || '').to.contain('LND has no wallet')
        T.expect(movedOn).to.equal(false)
        T.expect(fs.readFileSync(restore.getCheckpointPath(), 'utf8')).to.equal('DB_COMMITTED')
    } finally {
        dest.Stop()
        fs.rmSync(dataDir, { recursive: true, force: true })
    }
    T.d('a resume after DB_COMMITTED is refused when LND has no wallet')
}

const testResumeCleanDbRefused = async (T: StorageTestBase) => {
    T.d('starting testResumeCleanDbRefused')
    const dest = await openSecondStorage()
    const dataDir = dest.getStorageSettings().dataDir
    try {
        const settings = new SettingsManager(dest)
        await settings.InitSettings()
        let movedOn = false
        const unlocker = {
            WalletExists: async () => true,
            Restore: async () => { movedOn = true; return { adminMacaroon: '' } },
            PostRestore: async () => { movedOn = true },
            ApplyScb: async () => { movedOn = true },
        } as unknown as Unlocker
        const restore = new RestoreManager(dest, settings, unlocker)
        fs.mkdirSync(dataDir, { recursive: true })
        fs.writeFileSync(restore.getCheckpointPath(), 'DB_COMMITTED')
        fs.writeFileSync(restore.getPhraseHashPath(), hashRestorePhrase(TEST_PHRASE))
        T.expect(await dest.IsDbClean()).to.equal(true)
        const result = await restore.RestoreFromSource({
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: path.join(dataDir, 'missing-backup') },
        })
        T.expect(result.success).to.equal(false)
        T.expect(result.error || '').to.contain('this database is empty')
        T.expect(result.error || '').to.contain('cannot continue')
        T.expect(movedOn).to.equal(false)
    } finally {
        dest.Stop()
        fs.rmSync(dataDir, { recursive: true, force: true })
    }
    T.d('a resume is refused when the checkpoint does not match this empty database')
}

const testResumeMissingPhraseRefused = async (T: StorageTestBase) => {
    T.d('starting testResumeMissingPhraseRefused')
    const dest = await openSecondStorage()
    const dataDir = dest.getStorageSettings().dataDir
    try {
        const settings = new SettingsManager(dest)
        await settings.InitSettings()
        await markDbImported(dest)
        let movedOn = false
        const unlocker = {
            WalletExists: async () => true,
            Restore: async () => { movedOn = true; return { adminMacaroon: '' } },
            PostRestore: async () => { movedOn = true },
            ApplyScb: async () => { movedOn = true },
        } as unknown as Unlocker
        const restore = new RestoreManager(dest, settings, unlocker)
        fs.mkdirSync(dataDir, { recursive: true })
        fs.writeFileSync(restore.getCheckpointPath(), 'DB_COMMITTED')
        const result = await restore.RestoreFromSource({
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: path.join(dataDir, 'missing-backup') },
        })
        T.expect(result.success).to.equal(false)
        T.expect(result.error || '').to.contain('missing its phrase binding')
        T.expect(movedOn).to.equal(false)
    } finally {
        dest.Stop()
        fs.rmSync(dataDir, { recursive: true, force: true })
    }
    T.d('a resume is refused when the phrase binding file is missing')
}

const testResumeLndActiveWithoutWalletPub = async (T: StorageTestBase) => {
    T.d('starting testResumeLndActiveWithoutWalletPub')
    const dest = await openSecondStorage()
    const dataDir = dest.getStorageSettings().dataDir
    try {
        const settings = new SettingsManager(dest)
        await settings.InitSettings()
        await markDbImported(dest)
        let movedOn = false
        const unlocker = {
            WalletExists: async () => true,
            Restore: async () => { movedOn = true; return { adminMacaroon: '' } },
            PostRestore: async () => { movedOn = true },
            ApplyScb: async () => { movedOn = true },
        } as unknown as Unlocker
        const restore = new RestoreManager(dest, settings, unlocker)
        fs.mkdirSync(dataDir, { recursive: true })
        fs.writeFileSync(restore.getCheckpointPath(), 'LND_ACTIVE')
        fs.writeFileSync(restore.getPhraseHashPath(), hashRestorePhrase(TEST_PHRASE))
        const result = await restore.RestoreFromSource({
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: path.join(dataDir, 'missing-backup') },
        })
        T.expect(result.success).to.equal(false)
        T.expect(result.error || '').to.contain('never recorded which wallet')
        T.expect(movedOn).to.equal(false)
    } finally {
        dest.Stop()
        fs.rmSync(dataDir, { recursive: true, force: true })
    }
    T.d('a resume at LND_ACTIVE is refused when the wallet pub was never recorded')
}

const testResumeWalletMismatch = async (T: StorageTestBase) => {
    T.d('starting testResumeWalletMismatch')
    const dir = tempBackupDir()
    const dest = await openSecondStorage()
    const dataDir = dest.getStorageSettings().dataDir
    try {
        const sourceSettings = new SettingsManager(T.storage)
        await sourceSettings.InitSettings()
        await seedDialtone(T, sourceSettings)
        await writeLocalBackup(T, dir, 4)
        const settings = new SettingsManager(dest)
        await settings.InitSettings()
        await markDbImported(dest)
        let movedOn = false
        const unlocker = {
            WalletExists: async () => true,
            Restore: async () => { movedOn = true; return { adminMacaroon: '' } },
            PostRestore: async (_seed: string[], _mac: string | undefined, expectedPub?: string | null) => {
                if (expectedPub && expectedPub !== OTHER_WALLET_PUB) {
                    throw new Error('LND wallet does not match the wallet this restore started. This restore cannot continue. Delete .restore_checkpoint, .restore_phrase_hash, and .restore_wallet_pub, reset LND and the database, then retry from a clean node.')
                }
                movedOn = true
                return OTHER_WALLET_PUB
            },
            ApplyScb: async () => { movedOn = true },
        } as unknown as Unlocker
        const restore = new RestoreManager(dest, settings, unlocker)
        fs.mkdirSync(dataDir, { recursive: true })
        fs.writeFileSync(restore.getCheckpointPath(), 'LND_ACTIVE')
        fs.writeFileSync(restore.getPhraseHashPath(), hashRestorePhrase(TEST_PHRASE))
        fs.writeFileSync(restore.getWalletPubPath(), TEST_WALLET_PUB)
        const result = await restore.RestoreFromSource({
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: dir },
        })
        T.expect(result.success).to.equal(false)
        T.expect(result.error || '').to.contain('does not match the wallet this restore started')
        T.expect(result.error || '').to.contain('cannot continue')
        T.expect(movedOn).to.equal(false)
        T.expect(fs.readFileSync(restore.getCheckpointPath(), 'utf8')).to.equal('LND_ACTIVE')
    } finally {
        dest.Stop()
        fs.rmSync(dataDir, { recursive: true, force: true })
        fs.rmSync(dir, { recursive: true, force: true })
    }
    T.d('a resume is refused when LND is a different wallet than the one restore started')
}

const testWrongPhraseLeavesNoCheckpoint = async (T: StorageTestBase) => {
    T.d('starting testWrongPhraseLeavesNoCheckpoint')
    const dir = tempBackupDir()
    const dest = await openSecondStorage()
    const dataDir = dest.getStorageSettings().dataDir
    try {
        await writeLocalBackup(T, dir, 4)
        const settings = new SettingsManager(dest)
        await settings.InitSettings()
        let movedOn = false
        const unlocker = {
            WalletExists: async () => false,
            Restore: async () => { movedOn = true; return { adminMacaroon: '' } },
            PostRestore: async () => { movedOn = true },
            ApplyScb: async () => { movedOn = true },
        } as unknown as Unlocker
        const restore = new RestoreManager(dest, settings, unlocker)
        fs.mkdirSync(dataDir, { recursive: true })
        const result = await restore.RestoreFromSource({
            phrase: OTHER_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: dir },
        })
        T.expect(result.success).to.equal(false)
        T.expect(movedOn).to.equal(false)
        T.expect(fs.existsSync(restore.getCheckpointPath())).to.equal(false)
        T.expect(fs.existsSync(restore.getPhraseHashPath())).to.equal(false)
        T.expect(restore.IsRecoveryActive()).to.equal(false)
    } finally {
        dest.Stop()
        fs.rmSync(dataDir, { recursive: true, force: true })
        fs.rmSync(dir, { recursive: true, force: true })
    }
    T.d('a phrase that cannot decrypt a local backup leaves no checkpoint or phrase binding')
}

const testScbFailureKeepsCheckpoint = async (T: StorageTestBase) => {
    T.d('starting testScbFailureKeepsCheckpoint')
    const dir = tempBackupDir()
    const dest = await openSecondStorage()
    const dataDir = dest.getStorageSettings().dataDir
    try {
        const sourceSettings = new SettingsManager(T.storage)
        await sourceSettings.InitSettings()
        await seedDialtone(T, sourceSettings)
        await writeLocalBackup(T, dir, 4)
        const settings = new SettingsManager(dest)
        await settings.InitSettings()
        await markDbImported(dest)
        const unlocker = {
            WalletExists: async () => true,
            Restore: async () => { throw new Error('should not Restore on resume') },
            PostRestore: async () => TEST_WALLET_PUB,
            ApplyScb: async () => { throw new Error('ApplyScb failed') },
        } as unknown as Unlocker
        const restore = new RestoreManager(dest, settings, unlocker)
        fs.mkdirSync(dataDir, { recursive: true })
        fs.writeFileSync(restore.getCheckpointPath(), 'DB_COMMITTED')
        fs.writeFileSync(restore.getPhraseHashPath(), hashRestorePhrase(TEST_PHRASE))
        const result = await restore.RestoreFromSource({
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: dir },
        })
        T.expect(result.success).to.equal(false)
        T.expect(result.scb_restored).to.equal(false)
        T.expect(result.error || '').to.contain('ApplyScb failed')
        T.expect(fs.readFileSync(restore.getCheckpointPath(), 'utf8')).to.equal('LND_ACTIVE')
        T.expect(fs.existsSync(restore.getPhraseHashPath())).to.equal(true)
        T.expect(fs.readFileSync(restore.getWalletPubPath(), 'utf8').trim()).to.equal(TEST_WALLET_PUB)
        T.expect(restore.HasOngoingRecovery()).to.equal(true)
    } finally {
        dest.Stop()
        fs.rmSync(dataDir, { recursive: true, force: true })
        fs.rmSync(dir, { recursive: true, force: true })
    }
}

const testScbRetryCompletes = async (T: StorageTestBase) => {
    T.d('starting testScbRetryCompletes')
    const dir = tempBackupDir()
    const dest = await openSecondStorage()
    const dataDir = dest.getStorageSettings().dataDir
    try {
        const sourceSettings = new SettingsManager(T.storage)
        await sourceSettings.InitSettings()
        await seedDialtone(T, sourceSettings)
        await writeLocalBackup(T, dir, 4)
        const settings = new SettingsManager(dest)
        await settings.InitSettings()
        await markDbImported(dest)
        let applyCalls = 0
        const unlocker = {
            WalletExists: async () => true,
            Restore: async () => { throw new Error('should not Restore on resume') },
            PostRestore: async () => TEST_WALLET_PUB,
            ApplyScb: async () => {
                applyCalls++
                if (applyCalls <= 2) {
                    // First RestoreFromSource: restoreScb tries twice and fails both times.
                    throw new Error('ApplyScb failed')
                }
            },
        } as unknown as Unlocker
        const restore = new RestoreManager(dest, settings, unlocker)
        fs.mkdirSync(dataDir, { recursive: true })
        fs.writeFileSync(restore.getCheckpointPath(), 'DB_COMMITTED')
        fs.writeFileSync(restore.getPhraseHashPath(), hashRestorePhrase(TEST_PHRASE))
        const failed = await restore.RestoreFromSource({
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: dir },
        })
        T.expect(failed.success).to.equal(false)
        T.expect(fs.readFileSync(restore.getCheckpointPath(), 'utf8')).to.equal('LND_ACTIVE')

        const waitDone = restore.WaitForRecoveryCompletion()
        const ok = await restore.RestoreFromSource({
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: dir },
        })
        await waitDone
        T.expect(ok.success).to.equal(true)
        T.expect(ok.scb_restored).to.equal(true)
        T.expect(fs.readFileSync(restore.getCheckpointPath(), 'utf8')).to.equal('COMPLETED')
        T.expect(fs.existsSync(restore.getPhraseHashPath())).to.equal(false)
        T.expect(fs.existsSync(restore.getWalletPubPath())).to.equal(false)
        T.expect(restore.HasOngoingRecovery()).to.equal(false)
        T.expect(restore.IsRecoveryActive()).to.equal(false)
    } finally {
        dest.Stop()
        fs.rmSync(dataDir, { recursive: true, force: true })
        fs.rmSync(dir, { recursive: true, force: true })
    }
}

const testCompletedDoesNotHangStartupWaiter = async (T: StorageTestBase) => {
    T.d('starting testCompletedDoesNotHangStartupWaiter')
    const dir = tempBackupDir()
    const dest = await openSecondStorage()
    const dataDir = dest.getStorageSettings().dataDir
    try {
        const sourceSettings = new SettingsManager(T.storage)
        await sourceSettings.InitSettings()
        await seedDialtone(T, sourceSettings)
        await writeLocalBackup(T, dir, 4)
        const settings = new SettingsManager(dest)
        await settings.InitSettings()
        await markDbImported(dest)
        const unlocker = {
            WalletExists: async () => true,
            Restore: async () => { throw new Error('should not Restore on resume') },
            PostRestore: async () => TEST_WALLET_PUB,
            ApplyScb: async () => { },
        } as unknown as Unlocker
        const restore = new RestoreManager(dest, settings, unlocker)
        fs.mkdirSync(dataDir, { recursive: true })
        fs.writeFileSync(restore.getCheckpointPath(), 'DB_COMMITTED')
        fs.writeFileSync(restore.getPhraseHashPath(), hashRestorePhrase(TEST_PHRASE))

        const origUpdate = restore.updateCheckpoint
        let extraWait: Promise<void> | undefined
        ;(restore as any).updateCheckpoint = (current: string) => {
            origUpdate(current as Parameters<typeof origUpdate>[0])
            if (current === 'COMPLETED' && !extraWait) {
                extraWait = restore.WaitForRecoveryCompletion()
            }
        }

        const result = await restore.RestoreFromSource({
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: dir },
        })
        T.expect(result.success).to.equal(true)
        T.expect(!!extraWait).to.equal(true)
        await withTimeout(extraWait!, 1000, 'startup waiter hung after COMPLETED while restoreInFlight was still true')
        T.expect(restore.IsRecoveryActive()).to.equal(false)
    } finally {
        dest.Stop()
        fs.rmSync(dataDir, { recursive: true, force: true })
        fs.rmSync(dir, { recursive: true, force: true })
    }
    T.d('writing COMPLETED does not leave a waiter armed while restore is still in flight')
}

const testHasOngoingRecovery = async (T: StorageTestBase) => {
    T.d('starting testHasOngoingRecovery')
    const dest = await openSecondStorage()
    const dataDir = dest.getStorageSettings().dataDir
    try {
        const settings = new SettingsManager(dest)
        await settings.InitSettings()
        const restore = new RestoreManager(dest, settings, {} as Unlocker)
        fs.mkdirSync(dataDir, { recursive: true })
        T.expect(restore.HasOngoingRecovery()).to.equal(false)

        fs.writeFileSync(restore.getCheckpointPath(), 'STARTED')
        T.expect(restore.HasOngoingRecovery()).to.equal(true)

        fs.writeFileSync(restore.getCheckpointPath(), 'DB_COMMITTED')
        T.expect(restore.HasOngoingRecovery()).to.equal(true)

        fs.writeFileSync(restore.getCheckpointPath(), 'COMPLETED')
        T.expect(restore.HasOngoingRecovery()).to.equal(false)
    } finally {
        dest.Stop()
        fs.rmSync(dataDir, { recursive: true, force: true })
    }
}

const testConcurrentRestoreRejected = async (T: StorageTestBase) => {
    T.d('starting testConcurrentRestoreRejected')
    const dir = tempBackupDir()
    const dest = await openSecondStorage()
    const dataDir = dest.getStorageSettings().dataDir
    try {
        const sourceSettings = new SettingsManager(T.storage)
        await sourceSettings.InitSettings()
        await seedDialtone(T, sourceSettings)
        await writeLocalBackup(T, dir, 4)
        const settings = new SettingsManager(dest)
        await settings.InitSettings()
        await markDbImported(dest)
        let releasePostRestore: () => void = () => { }
        const postRestoreGate = new Promise<void>(resolve => { releasePostRestore = resolve })
        let enteredPostRestore: () => void = () => { }
        const inPostRestore = new Promise<void>(resolve => { enteredPostRestore = resolve })
        const unlocker = {
            WalletExists: async () => true,
            Restore: async () => ({ adminMacaroon: 'mac' }),
            PostRestore: async () => {
                enteredPostRestore()
                await postRestoreGate
                return TEST_WALLET_PUB
            },
            ApplyScb: async () => { },
        } as unknown as Unlocker
        const restore = new RestoreManager(dest, settings, unlocker)
        fs.mkdirSync(dataDir, { recursive: true })
        fs.writeFileSync(restore.getCheckpointPath(), 'DB_COMMITTED')
        fs.writeFileSync(restore.getPhraseHashPath(), hashRestorePhrase(TEST_PHRASE))
        const req: WizardTypes.RestoreRequest = {
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: dir },
        }
        const first = restore.RestoreFromSource(req)
        await inPostRestore
        const second = await restore.RestoreFromSource(req)
        T.expect(second.success).to.equal(false)
        T.expect(second.error || '').to.contain('already in progress')
        releasePostRestore()
        const firstResult = await first
        T.expect(firstResult.success).to.equal(true)
        T.expect(firstResult.scb_restored).to.equal(true)
    } finally {
        dest.Stop()
        fs.rmSync(dataDir, { recursive: true, force: true })
        fs.rmSync(dir, { recursive: true, force: true })
    }
}

const testGateNoDestination = async (T: StorageTestBase) => {
    T.d('starting testGateNoDestination')
    const settings = new SettingsManager(T.storage)
    await settings.InitSettings()
    settings.OverrideTestSettings(s => {
        s.backupSettings.localPath = ''
        s.backupSettings.cloudEnabled = false
        s.backupSettings.sftpEnabled = false
        return s
    })
    const backup = new BackupManager(T.storage, settings)
    await backup.InitKeys(TEST_SEED)
    settings.setBackupManager(backup)
    await backup.notifyBackupTable('admin_settings', 'applications')
    await backup.shutdown()
    T.d('no destination means notify/shutdown never push encrypted shards')
}

const testGateNoSeed = async (T: StorageTestBase) => {
    T.d('starting testGateNoSeed')
    const settings = new SettingsManager(T.storage)
    await settings.InitSettings()
    const dir = tempBackupDir()
    settings.OverrideTestSettings(s => {
        s.backupSettings.localPath = dir
        return s
    })
    const backup = new BackupManager(T.storage, settings)
    await backup.InitKeys([])
    await backup.notifyBackupTable('admin_settings')
    await backup.shutdown()
    T.expect(listEncFiles(dir)).to.deep.equal([])
    fs.rmSync(dir, { recursive: true, force: true })
    T.d('empty seed means backups stay no-ops even with localPath')
}

const testUploadAllTablesWritesEveryShard = async (T: StorageTestBase) => {
    T.d('starting testUploadAllTablesWritesEveryShard')
    const dir = tempBackupDir()
    const backup = new BackupManager(T.storage, await localBackupSettings(T, dir))
    try {
        await backup.InitKeys(TEST_SEED)
        await seedDialtone(T, backup.settings)
        await backup.AddressUpdate(5)
        backup.ChannelBackupUpdate(SAMPLE_SCB)
        await backup.uploadAllTables()
        const expectedFiles = BACKUP_TABLE_IDS.map(backupTableFilename).sort()
        T.expect(listEncFiles(dir)).to.deep.equal(expectedFiles)
        T.expect(await readAddressCount(dir)).to.equal(5)
        const row = await readIndexesRow(dir)
        T.expect(Buffer.from(row.scb ?? []).equals(SAMPLE_SCB)).to.equal(true)
    } finally {
        await backup.shutdown()
        fs.rmSync(dir, { recursive: true, force: true })
    }
    T.d('uploadAllTables writes every shard immediately, including indexes once both snapshots exist')
}

const testUploadAllTablesWithoutSnapshotsOmitsIndexes = async (T: StorageTestBase) => {
    T.d('starting testUploadAllTablesWithoutSnapshotsOmitsIndexes')
    const dir = tempBackupDir()
    const backup = new BackupManager(T.storage, await localBackupSettings(T, dir))
    try {
        await backup.InitKeys(TEST_SEED)
        await backup.uploadAllTables()
        T.expect(listEncFiles(dir)).to.deep.equal([])
    } finally {
        await backup.shutdown()
        fs.rmSync(dir, { recursive: true, force: true })
    }
    T.d('a full snapshot without address/channel state leaves previous files in place')
}

const testAtomicLocalReplace = async (T: StorageTestBase) => {
    T.d('starting testAtomicLocalReplace')
    const dir = tempBackupDir()
    try {
        const dest = path.join(dir, 'user_balances.enc')
        fs.writeFileSync(dest, Buffer.from('good-copy'))
        atomicWriteFile(dest, Buffer.from('next-copy'))
        T.expect(fs.readFileSync(dest, 'utf8')).to.equal('next-copy')
        T.expect(fs.existsSync(dest + '.part')).to.equal(false)
    } finally {
        fs.rmSync(dir, { recursive: true, force: true })
    }
    T.d('local replace writes a sibling then renames over the dest')
}

const testSnapshotPicksCompleteStagingGeneration = async (T: StorageTestBase) => {
    T.d('starting testSnapshotPicksCompleteStagingGeneration')
    const dir = tempBackupDir()
    try {
        await writeLocalBackup(T, dir, 4)
        const keys = await deriveBackupKeys(TEST_PHRASE)
        const copies = new Map<BackupTableId, { generation: number, data: Buffer }[]>()
        for (const id of BACKUP_TABLE_IDS) {
            const committed = fs.readFileSync(path.join(dir, backupTableFilename(id)))
            const { generation } = decryptTableShard(committed, keys.encKey)
            const staged = encryptTableRows(
                id === 'indexes' ? [encodeIndexesRow({ addressesCount: 99, scb: SAMPLE_SCB })] : decryptTableRows(committed, keys.encKey),
                keys.encKey,
                generation + 1,
            )
            fs.writeFileSync(path.join(dir, backupTableStagingFilename(id)), staged)
            copies.set(id, [
                { generation, data: committed },
                { generation: generation + 1, data: staged },
            ])
        }
        const picked = selectConsistentSnapshot(copies)
        const indexes = decryptTableRows(picked.get('indexes')!, keys.encKey).map(decodeIndexesRow)[0]
        T.expect(indexes.addressesCount).to.equal(99)

        const settings = new SettingsManager(T.storage)
        await settings.InitSettings()
        const restore = new RestoreManager(T.storage, settings, {} as Unlocker)
        const buffers = await restore.fetchSegmentsData({
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: dir },
        }, keys)
        T.expect(decodeIndexesRow(decryptTableRows(buffers.get('indexes')!, keys.encKey)[0]).addressesCount).to.equal(99)
    } finally {
        fs.rmSync(dir, { recursive: true, force: true })
    }
    T.d('a complete newer staging generation is preferred over the committed files')
}

const testSnapshotIgnoresIncompleteNewGeneration = async (T: StorageTestBase) => {
    T.d('starting testSnapshotIgnoresIncompleteNewGeneration')
    const dir = tempBackupDir()
    try {
        await writeLocalBackup(T, dir, 4)
        const keys = await deriveBackupKeys(TEST_PHRASE)
        const committed = fs.readFileSync(path.join(dir, backupTableFilename('indexes')))
        const { generation } = decryptTableShard(committed, keys.encKey)
        fs.writeFileSync(
            path.join(dir, backupTableStagingFilename('indexes')),
            encryptTableRows([encodeIndexesRow({ addressesCount: 99, scb: SAMPLE_SCB })], keys.encKey, generation + 1),
        )
        fs.writeFileSync(path.join(dir, backupTableStagingFilename('products')), Buffer.from('truncated'))
        const settings = new SettingsManager(T.storage)
        await settings.InitSettings()
        const restore = new RestoreManager(T.storage, settings, {} as Unlocker)
        const buffers = await restore.fetchSegmentsData({
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: dir },
        }, keys)
        T.expect(decodeIndexesRow(decryptTableRows(buffers.get('indexes')!, keys.encKey)[0]).addressesCount).to.equal(4)
    } finally {
        fs.rmSync(dir, { recursive: true, force: true })
    }
    T.d('an incomplete or truncated new generation leaves the previous good snapshot in place')
}

const testSnapshotRejectsMixedGenerations = async (T: StorageTestBase) => {
    T.d('starting testSnapshotRejectsMixedGenerations')
    const copies = new Map<BackupTableId, { generation: number, data: Buffer }[]>()
    for (const id of BACKUP_TABLE_IDS) {
        copies.set(id, [{ generation: id === 'application_users' ? 2 : 1, data: Buffer.from(id) }])
    }
    let message = ''
    try {
        selectConsistentSnapshot(copies)
    } catch (err: any) {
        message = err.message
    }
    T.expect(message).to.include('incomplete backup snapshot')
    T.d('shards from different generations are not mixed into a restore set')
}

const localBackupSettings = async (T: StorageTestBase, dir: string) => {
    const settings = new SettingsManager(T.storage)
    await settings.InitSettings()
    settings.OverrideTestSettings(s => {
        s.backupSettings.localPath = dir
        s.backupSettings.cloudEnabled = false
        s.backupSettings.sftpEnabled = false
        return s
    })
    return settings
}

const seedDialtone = async (T: StorageTestBase, settings: SettingsManager) => {
    const defaultName = settings.getSettings().serviceSettings.defaultAppName
    let app = pickDefaultApp(await T.storage.applicationStorage.GetApplications(), defaultName)
    if (!app) {
        app = await T.storage.applicationStorage.AddApplication(defaultName, true)
    }
    await T.storage.applicationStorage.GenerateApplicationKeys(app)
    app = await T.storage.applicationStorage.GetApplication(app.app_id)

    const user = await T.storage.applicationStorage.AddApplicationUser(app, crypto.randomBytes(32).toString('hex'), 1234)
    await T.storage.applicationStorage.UpdateAppUserMessagingToken(user.identifier, 'aa'.repeat(16), 'token-1')
    await T.storage.offerStorage.AddDefaultUserOffer(user.identifier)
    await T.storage.productStorage.AddProduct('backup-product', 50, user.user)
    await T.storage.debitStorage.AddDebitAccess(user.identifier, {
        npub: 'b'.repeat(64),
        authorize: true,
    })
    await T.storage.managementStorage.addGrant(user.identifier, 'c'.repeat(64), false, 0)
    await T.storage.applicationStorage.AddInviteToken(app, 100)
    await T.storage.liquidityStorage.CreateTrackedProvider('lnPub', crypto.randomBytes(32).toString('hex'), 42)
    await settings.updateLspChannelThreshold(1_500_000)

    return { app, user }
}

const testLocalRoundtrip = async (T: StorageTestBase) => {
    T.d('starting testLocalRoundtrip')
    const dir = tempBackupDir()
    const settings = new SettingsManager(T.storage)
    await settings.InitSettings()
    settings.OverrideTestSettings(s => {
        s.backupSettings.localPath = dir
        s.backupSettings.cloudEnabled = false
        s.backupSettings.sftpEnabled = false
        return s
    })

    const backup = new BackupManager(T.storage, settings)
    await backup.InitKeys(TEST_SEED)
    settings.setBackupManager(backup)

    const { app, user } = await seedDialtone(T, settings)
    await backup.AddressUpdate(17)
    backup.ChannelBackupUpdate(SAMPLE_SCB)
    await backup.shutdown()

    const expectedFiles = BACKUP_TABLE_IDS.map(backupTableFilename).sort()
    T.expect(listEncFiles(dir)).to.deep.equal(expectedFiles)

    const before = {
        applications: sortBy(await T.storage.applicationStorage.ExportApplications(), r => r.app_id),
        applicationUsers: sortBy(await T.storage.applicationStorage.ExportApplicationUsers(), r => r.identifier),
        balances: sortBy(await T.storage.userStorage.ExportBalances(), r => r.user_id),
        adminSettings: sortBy(await T.storage.settingsStorage.ExportSettings(), r => r.env_name),
        userOffers: sortBy(await T.storage.offerStorage.ExportUserOffers(), r => r.offer_id),
        products: sortBy(await T.storage.productStorage.ExportProducts(), r => r.product_id),
        debitAccesses: sortBy(await T.storage.debitStorage.ExportDebitAccess(), r => `${r.app_user_id}:${r.npub}`),
        managementGrants: sortBy(await T.storage.managementStorage.ExportManagementGrants(), r => `${r.app_user_id}:${r.app_pubkey}`),
        inviteTokens: sortBy(await T.storage.applicationStorage.ExportInviteTokens(), r => r.inviteToken),
        appUserDevices: sortBy(await T.storage.applicationStorage.ExportAppUserDevices(), r => `${r.app_user_id}:${r.device_id}`),
        trackedProviders: sortBy(await T.storage.liquidityStorage.ExportTrackedProviders(), r => `${r.provider_type}:${r.provider_pubkey}`),
    }
    T.expect(before.applications.some(a => a.app_id === app.app_id && !!a.nostr_public_key)).to.equal(true)
    T.expect(before.balances.some(b => b.user_id === user.user.user_id && b.balance_sats === 1234)).to.equal(true)
    T.expect(before.adminSettings.some(s => s.env_name === 'LSP_CHANNEL_THRESHOLD' && s.env_value === '1500000')).to.equal(true)

    const dest = await openSecondStorage()
    T.expect(await dest.IsDbClean()).to.equal(true)
    const destSettings = new SettingsManager(dest)
    await destSettings.InitSettings()
    const restore = new RestoreManager(dest, destSettings, {} as Unlocker)
    const keys = await deriveBackupKeys(TEST_PHRASE)
    const req: WizardTypes.RestoreRequest = {
        phrase: TEST_PHRASE,
        source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: dir },
    }
    const buffers = await restore.fetchSegmentsData(req, keys)
    T.expect(buffers.size).to.equal(BACKUP_TABLE_IDS.length)
    const { backupData } = restore.decodeSegmentsData(buffers, keys)
    T.expect(backupData.indexes[0]?.addressesCount).to.equal(17)
    T.expect(Buffer.from(backupData.indexes[0]?.scb ?? []).equals(SAMPLE_SCB)).to.equal(true)

    await dest.StartTransaction(async tx => {
        await restore.importDialtone(backupData, tx)
    }, 'backup-local-restore')

    const after = {
        applications: sortBy(await dest.applicationStorage.ExportApplications(), r => r.app_id),
        applicationUsers: sortBy(await dest.applicationStorage.ExportApplicationUsers(), r => r.identifier),
        balances: sortBy(await dest.userStorage.ExportBalances(), r => r.user_id),
        adminSettings: sortBy(await dest.settingsStorage.ExportSettings(), r => r.env_name),
        userOffers: sortBy(await dest.offerStorage.ExportUserOffers(), r => r.offer_id),
        products: sortBy(await dest.productStorage.ExportProducts(), r => r.product_id),
        debitAccesses: sortBy(await dest.debitStorage.ExportDebitAccess(), r => `${r.app_user_id}:${r.npub}`),
        managementGrants: sortBy(await dest.managementStorage.ExportManagementGrants(), r => `${r.app_user_id}:${r.app_pubkey}`),
        inviteTokens: sortBy(await dest.applicationStorage.ExportInviteTokens(), r => r.inviteToken),
        appUserDevices: sortBy(await dest.applicationStorage.ExportAppUserDevices(), r => `${r.app_user_id}:${r.device_id}`),
        trackedProviders: sortBy(await dest.liquidityStorage.ExportTrackedProviders(), r => `${r.provider_type}:${r.provider_pubkey}`),
    }

    // Dest InitSettings may add extra admin_settings rows; assert source rows are present.
    for (const row of before.adminSettings) {
        const found = after.adminSettings.find(s => s.env_name === row.env_name)
        T.expect(found?.env_value).to.equal(row.env_value)
    }
    T.expect(after.applications).to.deep.equal(before.applications)
    T.expect(after.applicationUsers).to.deep.equal(before.applicationUsers)
    T.expect(after.balances).to.deep.equal(before.balances)
    T.expect(after.userOffers).to.deep.equal(before.userOffers)
    T.expect(after.products).to.deep.equal(before.products)
    T.expect(after.debitAccesses).to.deep.equal(before.debitAccesses)
    T.expect(after.managementGrants).to.deep.equal(before.managementGrants)
    T.expect(after.inviteTokens).to.deep.equal(before.inviteTokens)
    T.expect(after.appUserDevices).to.deep.equal(before.appUserDevices)
    T.expect(after.trackedProviders).to.deep.equal(before.trackedProviders)

    dest.Stop()
    fs.rmSync(dir, { recursive: true, force: true })
    T.d('local backup shards restore dialtone state')
}

const SAMPLE_SCB = Buffer.from('multi-chan-backup'.repeat(40))

/** scb: bytes, null for a node without channels, or 'unknown' when LND never reported channel state. */
const writeLocalBackup = async (T: StorageTestBase, dir: string, addressCount?: number, scb: Uint8Array | null | 'unknown' = SAMPLE_SCB) => {
    const settings = new SettingsManager(T.storage)
    await settings.InitSettings()
    settings.OverrideTestSettings(s => {
        s.backupSettings.localPath = dir
        s.backupSettings.cloudEnabled = false
        s.backupSettings.sftpEnabled = false
        return s
    })
    const backup = new BackupManager(T.storage, settings)
    await backup.InitKeys(TEST_SEED)
    if (addressCount !== undefined) {
        await backup.AddressUpdate(addressCount)
    }
    if (scb !== 'unknown') {
        backup.ChannelBackupUpdate(scb)
    }
    await backup.shutdown()
}

const rewriteTableShard = async (dir: string, id: BackupTableId, rows: Uint8Array[]) => {
    const keys = await deriveBackupKeys(TEST_PHRASE)
    const file = path.join(dir, backupTableFilename(id))
    const { generation } = decryptTableShard(fs.readFileSync(file), keys.encKey)
    fs.writeFileSync(file, encryptTableRows(rows, keys.encKey, generation))
}

const testMissingShardFailsClosed = async (T: StorageTestBase) => {
    T.d('starting testMissingShardFailsClosed')
    const dir = tempBackupDir()
    try {
        await writeLocalBackup(T, dir, 3)
        fs.rmSync(path.join(dir, backupTableFilename('user_balances')))
        const settings = new SettingsManager(T.storage)
        await settings.InitSettings()
        const restore = new RestoreManager(T.storage, settings, {} as Unlocker)
        const keys = await deriveBackupKeys(TEST_PHRASE)
        const req: WizardTypes.RestoreRequest = {
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: dir },
        }
        let message = ''
        try {
            await restore.fetchSegmentsData(req, keys)
        } catch (err: any) {
            message = err.message
        }
        T.expect(message).to.equal(failureMessage(WizardTypes.RestoreRequest_source_type.LOCAL_PATH, 'user_balances'))
        let decodeThrew = false
        try {
            restore.decodeSegmentsData(new Map(), keys)
        } catch (err: any) {
            decodeThrew = true
            T.expect(err.message).to.include('missing backup shard')
        }
        T.expect(decodeThrew).to.equal(true)
    } finally {
        fs.rmSync(dir, { recursive: true, force: true })
    }
    T.d('a missing shard file fails the restore before import')
}

const testEmptyProductsShardImports = async (T: StorageTestBase) => {
    T.d('starting testEmptyProductsShardImports')
    const dir = tempBackupDir()
    const dest = await openSecondStorage()
    const dataDir = dest.getStorageSettings().dataDir
    try {
        await writeLocalBackup(T, dir, 4)
        const keys = await deriveBackupKeys(TEST_PHRASE)
        await rewriteTableShard(dir, 'products', [])
        const destSettings = new SettingsManager(dest)
        await destSettings.InitSettings()
        const restore = new RestoreManager(dest, destSettings, {} as Unlocker)
        const req: WizardTypes.RestoreRequest = {
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: dir },
        }
        const buffers = await restore.fetchSegmentsData(req, keys)
        const { backupData } = restore.decodeSegmentsData(buffers, keys)
        T.expect(backupData.products).to.deep.equal([])
        await dest.StartTransaction(async tx => {
            await restore.importDialtone(backupData, tx)
        }, 'backup-empty-products')
        T.expect(await dest.productStorage.ExportProducts()).to.deep.equal([])
        T.expect((await dest.userStorage.ExportBalances()).length).to.be.greaterThan(0)
    } finally {
        dest.Stop()
        fs.rmSync(dataDir, { recursive: true, force: true })
        fs.rmSync(dir, { recursive: true, force: true })
    }
    T.d('an empty products shard imports and leaves the other tables in place')
}

const readAddressCount = async (dir: string) => {
    const file = path.join(dir, backupTableFilename('indexes'))
    if (!fs.existsSync(file)) return undefined
    const keys = await deriveBackupKeys(TEST_PHRASE)
    const rows = decryptTableRows(fs.readFileSync(file), keys.encKey).map(decodeIndexesRow)
    return rows[0]?.addressesCount
}

const testIndexesWithoutAddressUpdate = async (T: StorageTestBase) => {
    T.d('starting testIndexesWithoutAddressUpdate')
    const dir = tempBackupDir()
    try {
        await writeLocalBackup(T, dir)
        T.expect(listEncFiles(dir)).to.deep.equal([])
        const settings = new SettingsManager(T.storage)
        await settings.InitSettings()
        const restore = new RestoreManager(T.storage, settings, {} as Unlocker)
        const keys = await deriveBackupKeys(TEST_PHRASE)
        const req: WizardTypes.RestoreRequest = {
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: dir },
        }
        let message = ''
        try {
            await restore.fetchSegmentsData(req, keys)
        } catch (err: any) {
            message = err.message
        }
        T.expect(message).to.include(failureMessage(WizardTypes.RestoreRequest_source_type.LOCAL_PATH, 'indexes'))
    } finally {
        fs.rmSync(dir, { recursive: true, force: true })
    }
    T.d('a backup with no address snapshot writes nothing, so the previous copy is kept')
}

const testIndexesZeroSnapshot = async (T: StorageTestBase) => {
    T.d('starting testIndexesZeroSnapshot')
    const dir = tempBackupDir()
    try {
        await writeLocalBackup(T, dir, 0)
        T.expect(await readAddressCount(dir)).to.equal(0)
    } finally {
        fs.rmSync(dir, { recursive: true, force: true })
    }
    T.d('a snapshot of zero addresses is written')
}

const testEmptyIndexesShardFails = async (T: StorageTestBase) => {
    T.d('starting testEmptyIndexesShardFails')
    const dir = tempBackupDir()
    const dest = await openSecondStorage()
    const dataDir = dest.getStorageSettings().dataDir
    try {
        await writeLocalBackup(T, dir, 4)
        await rewriteTableShard(dir, 'indexes', [])
        const destSettings = new SettingsManager(dest)
        await destSettings.InitSettings()
        let movedOn = false
        const unlocker = {
            WalletExists: async () => false,
            Restore: async () => { movedOn = true; return { adminMacaroon: '' } },
            PostRestore: async () => { movedOn = true },
            ApplyScb: async () => { movedOn = true },
        } as unknown as Unlocker
        const restore = new RestoreManager(dest, destSettings, unlocker)
        const result = await restore.RestoreFromSource({
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: dir },
        })
        T.expect(result.success).to.equal(false)
        T.expect(result.error || '').to.contain('one address count')
        T.expect(movedOn).to.equal(false)
    } finally {
        dest.Stop()
        fs.rmSync(dataDir, { recursive: true, force: true })
        fs.rmSync(dir, { recursive: true, force: true })
    }
    T.d('an indexes shard with no row fails restore before LND or channel backup')
}

const testIndexesUnknownDoesNotClobber = async (T: StorageTestBase) => {
    T.d('starting testIndexesUnknownDoesNotClobber')
    const dir = tempBackupDir()
    try {
        await writeLocalBackup(T, dir, 17)
        await writeLocalBackup(T, dir)
        T.expect(await readAddressCount(dir)).to.equal(17)
    } finally {
        fs.rmSync(dir, { recursive: true, force: true })
    }
    T.d('shutdown without a snapshot leaves the stored address count in place')
}

const readIndexesRow = async (dir: string) => {
    const keys = await deriveBackupKeys(TEST_PHRASE)
    const file = path.join(dir, backupTableFilename('indexes'))
    return decryptTableRows(fs.readFileSync(file), keys.encKey).map(decodeIndexesRow)[0]
}

const testChannelStateUnknownDoesNotClobber = async (T: StorageTestBase) => {
    T.d('starting testChannelStateUnknownDoesNotClobber')
    const dir = tempBackupDir()
    try {
        // A known address count alone must not upload: it would replace a stored SCB with "no channels".
        await writeLocalBackup(T, dir, 9, 'unknown')
        T.expect(fs.existsSync(path.join(dir, backupTableFilename('indexes')))).to.equal(false)

        await writeLocalBackup(T, dir, 9, SAMPLE_SCB)
        await writeLocalBackup(T, dir, 12, 'unknown')
        const row = await readIndexesRow(dir)
        T.expect(row.addressesCount).to.equal(9)
        T.expect(Buffer.from(row.scb ?? []).equals(SAMPLE_SCB)).to.equal(true)
    } finally {
        fs.rmSync(dir, { recursive: true, force: true })
    }
    T.d('indexes.enc is only written once both the address count and the channel state are known')
}

const testIndexesScbRoundtrip = (T: StorageTestBase) => {
    T.d('starting testIndexesScbRoundtrip')
    const withChannels = decodeIndexesRow(encodeIndexesRow({ addressesCount: 3, scb: SAMPLE_SCB }))
    T.expect(withChannels.addressesCount).to.equal(3)
    T.expect(Buffer.from(withChannels.scb ?? []).equals(SAMPLE_SCB)).to.equal(true)

    const noChannels = decodeIndexesRow(encodeIndexesRow({ addressesCount: 0, scb: null }))
    T.expect(noChannels.addressesCount).to.equal(0)
    T.expect(noChannels.scb).to.equal(null)

    let threw = false
    try {
        encodeIndexesRow({ addressesCount: 1, scb: new Uint8Array() })
    } catch {
        threw = true
    }
    T.expect(threw).to.equal(true)
    T.d('an SCB longer than one TLV value roundtrips, and null is the no-channels marker')
}

const testNoChannelsSkipsScbRestore = async (T: StorageTestBase) => {
    T.d('starting testNoChannelsSkipsScbRestore')
    const dir = tempBackupDir()
    const dest = await openSecondStorage()
    const dataDir = dest.getStorageSettings().dataDir
    try {
        const sourceSettings = new SettingsManager(T.storage)
        await sourceSettings.InitSettings()
        await seedDialtone(T, sourceSettings)
        await writeLocalBackup(T, dir, 4, null)
        const settings = new SettingsManager(dest)
        await settings.InitSettings()
        await markDbImported(dest)
        let applyCalls = 0
        const unlocker = {
            WalletExists: async () => true,
            Restore: async () => { throw new Error('should not Restore on resume') },
            PostRestore: async () => TEST_WALLET_PUB,
            ApplyScb: async () => { applyCalls++ },
        } as unknown as Unlocker
        const restore = new RestoreManager(dest, settings, unlocker)
        fs.mkdirSync(dataDir, { recursive: true })
        fs.writeFileSync(restore.getCheckpointPath(), 'DB_COMMITTED')
        fs.writeFileSync(restore.getPhraseHashPath(), hashRestorePhrase(TEST_PHRASE))
        const result = await restore.RestoreFromSource({
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: dir },
        })
        T.expect(result.error || '').to.equal('')
        T.expect(result.success).to.equal(true)
        T.expect(result.scb_restored).to.equal(false)
        T.expect(applyCalls).to.equal(0)
        T.expect(fs.readFileSync(restore.getCheckpointPath(), 'utf8')).to.equal('COMPLETED')
        T.expect(restore.HasOngoingRecovery()).to.equal(false)
    } finally {
        dest.Stop()
        fs.rmSync(dataDir, { recursive: true, force: true })
        fs.rmSync(dir, { recursive: true, force: true })
    }
    T.d('a backup that marks no channels completes without applying an SCB')
}

const testShardWithoutScbFieldFails = async (T: StorageTestBase) => {
    T.d('starting testShardWithoutScbFieldFails')
    const dir = tempBackupDir()
    const dest = await openSecondStorage()
    const dataDir = dest.getStorageSettings().dataDir
    try {
        await writeLocalBackup(T, dir, 4)
        const rowWithoutChannelBackup = encodeTLV({ 2: [integerToUint8Array(4)] })
        await rewriteTableShard(dir, 'indexes', [rowWithoutChannelBackup])
        const destSettings = new SettingsManager(dest)
        await destSettings.InitSettings()
        let movedOn = false
        const unlocker = {
            WalletExists: async () => false,
            Restore: async () => { movedOn = true; return { adminMacaroon: '' } },
            PostRestore: async () => { movedOn = true },
            ApplyScb: async () => { movedOn = true },
        } as unknown as Unlocker
        const restore = new RestoreManager(dest, destSettings, unlocker)
        const result = await restore.RestoreFromSource({
            phrase: TEST_PHRASE,
            source: { type: WizardTypes.RestoreRequest_source_type.LOCAL_PATH, local_path: dir },
        })
        T.expect(result.success).to.equal(false)
        T.expect(result.error || '').to.contain('no channel backup field')
        T.expect(movedOn).to.equal(false)
        T.expect(fs.existsSync(restore.getCheckpointPath())).to.equal(false)
        T.expect(fs.existsSync(restore.getPhraseHashPath())).to.equal(false)
    } finally {
        dest.Stop()
        fs.rmSync(dataDir, { recursive: true, force: true })
        fs.rmSync(dir, { recursive: true, force: true })
    }
    T.d('an indexes shard without the SCB field is refused rather than read as an empty wallet')
}

const testScbFromSnapshot = (T: StorageTestBase) => {
    T.d('starting testScbFromSnapshot')
    const blob = new Uint8Array([1, 2, 3])
    const point = { fundingTxid: { oneofKind: 'fundingTxidBytes', fundingTxidBytes: new Uint8Array(32) }, outputIndex: 0 } as any
    T.expect(scbFromSnapshot({})).to.equal(undefined)
    T.expect(scbFromSnapshot({ multiChanBackup: { chanPoints: [], multiChanBackup: blob } })).to.equal(null)
    T.expect(scbFromSnapshot({ multiChanBackup: { chanPoints: [point], multiChanBackup: new Uint8Array() } })).to.equal(undefined)
    T.expect(scbFromSnapshot({ multiChanBackup: { chanPoints: [point], multiChanBackup: blob } })).to.equal(blob)
    T.d('a snapshot without channels maps to the no-channels marker, channels without bytes stay unknown')
}

const testHookLspThreshold = async (T: StorageTestBase) => {
    T.d('starting testHookLspThreshold')
    const settings = new SettingsManager(T.storage)
    await settings.InitSettings()
    const spy = makeSpyBackup()
    settings.setBackupManager(spy)
    const next = settings.getSettings().lspSettings.channelThreshold === 0 ? 900_000 : 0
    const changed = await settings.updateLspChannelThreshold(next)
    T.expect(changed).to.equal(true)
    T.expect(spy.notified).to.include('admin_settings')
    T.d('updateLspChannelThreshold notifies admin_settings')
}

const testHookRemoteBackupEnable = async (T: StorageTestBase) => {
    T.d('starting testHookRemoteBackupEnable')
    const settings = new SettingsManager(T.storage)
    await settings.InitSettings()
    const spy = makeSpyBackup()
    settings.setBackupManager(spy)
    await settings.updateRemoteBackup({ enabled: false, host: '', port: 22, user: '', pass: '', host_fingerprint: '' })
    const changed = await settings.updateRemoteBackup({ enabled: true, host: '', port: 22, user: '', pass: '', host_fingerprint: '' })
    T.expect(changed).to.equal(true)
    T.expect(spy.fullUploads).to.equal(1)
    T.d('turning remote backup on uploads every table to the new destination')
}

const testHookDefaultAppRename = async (T: StorageTestBase) => {
    T.d('starting testHookDefaultAppRename')
    const settings = new SettingsManager(T.storage)
    await settings.InitSettings()
    settings.OverrideTestSettings(s => {
        s.swapsSettings.boltzHttpUrl = ''
        s.swapsSettings.boltzWebSocketUrl = ''
        s.swapsSettings.boltsHttpUrlAlt = ''
        s.swapsSettings.boltsWebSocketUrlAlt = ''
        return s
    })
    const admin = new AdminManager(settings, T.storage, new Swaps(settings, T.storage))
    const spy = makeSpyBackup()
    settings.setBackupManager(spy)
    admin.setBackupManager(spy)

    const name = settings.getSettings().serviceSettings.defaultAppName
    let app = pickDefaultApp(await T.storage.applicationStorage.GetApplications(), name)
    if (!app) {
        app = await T.storage.applicationStorage.AddApplication(name, true)
    }

    const newName = `renamed-${Date.now()}-${crypto.randomBytes(2).toString('hex')}`
    const current = await admin.GetAdminNodeSettings()
    await admin.UpdateAdminNodeSettings({
        node_name: newName,
        avatar_url: current.avatar_url,
        automate_liquidity: current.automate_liquidity,
        remote_backup: current.remote_backup,
        lsp_channel_threshold: current.lsp_channel_threshold,
    } as Types.UpdateAdminNodeSettingsRequest)

    T.expect(spy.notified).to.include('applications')
    T.expect(spy.notified).to.include('admin_settings')
    T.d('default app rename notifies applications and admin_settings')
}

const testHookEnrollCreate = async (T: StorageTestBase) => {
    T.d('starting testHookEnrollCreate')
    const settings = new SettingsManager(T.storage)
    await settings.InitSettings()
    settings.OverrideTestSettings(s => {
        s.nostrRelaySettings.enrollPowBits = 0
        if (!s.nostrRelaySettings.relays[0]) {
            s.nostrRelaySettings.relays = ['wss://relay.lightning.pub']
        }
        return s
    })
    const spy = makeSpyBackup()
    const enroll = new EnrollManager(T.storage, settings, spy)
    const app = await T.storage.applicationStorage.AddApplication(`enroll-backup-${Date.now()}`, true)
    const keys = await T.storage.applicationStorage.GenerateApplicationKeys(app)
    const pub = 'e'.repeat(64)
    const ctx = toClinkCtx({
        id: 'f'.repeat(64),
        pub,
        content: '{}',
        appId: keys.appId,
        startAtNano: '0',
        startAtMs: Date.now(),
        kind: CLINK_ENROLL_KIND,
        tags: [['p', keys.publicKey], ['clink_version', CLINK_VERSION]],
        created_at: Math.floor(Date.now() / 1000),
    })
    const ok = await enroll.HandleClinkEnroll(ctx, {})
    T.expect(ok?.res).to.equal('ok')
    T.expect(spy.notified).to.include('application_users')
    T.expect(spy.notified).to.include('user_balances')
    T.d('enroll create notifies application_users and user_balances')
}
