import { getLogger } from '../services/helpers/logger.js'
import { initSettings } from '../services/main/init.js'
import { LoadEliotLndSettingsFromEnv } from '../services/main/settings.js'
import { GetTestStorageSettings, StorageSettings } from '../services/storage/index.js'
import { defaultInvoiceExpiry } from '../services/storage/paymentStorage.js'
import { runSanityCheck, safelySetUserBalance, TestBase } from './testBase.js'
import { tryUntil } from './networkSetup.js'
import * as Types from '../../proto/autogenerated/ts/types.js'
import { LndNodeSettings } from '../services/main/settings.js'
import { NostrEvent, UnsignedEvent } from 'nostr-tools'
export const ignore = false
export const dev = true
const [eliotSettings, eliot2Settings] = LoadEliotLndSettingsFromEnv()
export const lndSettings: LndNodeSettings = eliotSettings
export const pushBackupsToNostr = true

export default async (T: TestBase) => {
    const seed = await T.main.unlocker.GetSeed()
    T.d("Wallet unlocked successfully, seed: " + seed.seed.join(" "))
    // await safelySetUserBalance(T, T.user1, 2000)
    let latestSCBEvent: UnsignedEvent | null = null
    T.main.attachNostrSend(async (initiator, data, relays) => {
        //console.log("got nostr send", initiator, data, relays)
        if (data.type === 'event') {
            console.log("got SCB event", data.event.content)
            latestSCBEvent = data.event
        }
    })

    await T.main.lnd.ConnectPeer(T.chainTools.carolInfo)
    T.d("Connected to carol")

    const pubkey = await tryUntil<string>(async i => {
        const info = await T.main.lnd.GetInfo()
        if (!info.syncedToChain) {
            throw new Error("eliot not synced to chain")
        }
        if (!info.syncedToGraph) {
            //await lnd.ConnectPeer({})
            throw new Error("eliot not synced to graph")
        }
        return info.identityPubkey
    }, 10, 8000)
    T.d("Eliot pubkey: " + pubkey)
    T.d("Funding wallet...")
    /* const otherBalance = await T.externalAccessToOtherLnd.GetBalance()
    T.d("Other balance: " + JSON.stringify(otherBalance))
    const thirdBalance = await T.externalAccessToThirdLnd.GetBalance()
    T.d("Third balance: " + JSON.stringify(thirdBalance)) */
    const addr = await T.main.lnd.NewAddress(Types.AddressType.WITNESS_PUBKEY_HASH, { useProvider: false, from: 'system' })
    await T.externalAccessToOtherLnd.PayAddress(addr.address, 200_000, 2, "test", { useProvider: false, from: 'system' })
    //await T.chainTools.sendToAddress(addr.address, 1_000_000)
    await T.chainTools.mine(3)
    T.d("Wallet funded")
    T.d("Checking balance...")
    let balance = await T.main.lnd.GetBalance()
    T.d("Balance: " + JSON.stringify(balance))
    T.d("Opening channel to carol...")
    await T.main.lnd.OpenChannel(T.chainTools.carolInfo.pubkey, addr.address, 100_000, 0, 1)
    await T.chainTools.mine(3)
    await T.chainTools.mine(3)
    T.d("Channel opened")
    const channels = await T.main.lnd.ListChannels()
    T.d("Channels: " + channels.channels.length + " " + channels.channels.map(c => c.active))
    const pendingChannels = await T.main.lnd.ListPendingChannels()
    T.d("Pending channels: " + pendingChannels.pendingOpenChannels.length)
    balance = await T.main.lnd.GetBalance()
    T.d("Balance: " + JSON.stringify(balance))
    T.d("shutting down...")
    T.main.lnd.Stop()
    await T.main.lnd.lightning.stopDaemon({})
    T.d("lnd stopped")
    if (!latestSCBEvent) {
        throw new Error("no SCB event found")
    }

    await recoverEliot(T, seed.seed, latestSCBEvent)
    T.d("recovery complete")
}

const recoverEliot = async (T: TestBase, seed: string[], scbEvent: UnsignedEvent) => {
    const storageSettings = GetTestStorageSettings()
    const initOk = await initSettings(getLogger({ component: "mainForTest" }), storageSettings)
    if (!initOk) {
        throw new Error("failed to initialize settings manager")
    }
    T.d("recovery settings manager initialized")
    const { settingsManager, unlocker } = initOk
    settingsManager.OverrideTestSettings(s => {
        s.liquiditySettings.disableLiquidityProvider = true
        s.liquiditySettings.liquidityProviderPub = ""
        s.liquiditySettings.useOnlyLiquidityProvider = false
        s.lndNodeSettings = eliot2Settings
        return s
    })
    await unlocker.Unlock({ seed })
    T.d("recovery wallet unlocked")
    await unlocker.ApplyScb(scbEvent.content)
    T.d("SCB applied")
    const info = await T.main.lnd.GetInfo()
    T.d("Eliot info: " + info.identityPubkey)
    const balance = await T.main.lnd.GetBalance()
    T.d("Balance: " + balance)
    const channels = await T.main.lnd.ListChannels()
    T.d("Channels: " + channels.channels.length + " " + channels.channels.map(c => c.active))
}