// BACKUP: Restore pipeline
//
// Clean-target semantics: restore refuses to run unless DB is freshly initialized
// (all dialtone tables empty). No upsert/merge — prevents ghost-state mess if
// someone runs restore against a half-initialized node.
//
// If LND already has a wallet and there is no resumable checkpoint (DB_COMMITTED /
// LND_ACTIVE), restore returns immediately. Resume after those checkpoints is
// allowed only when the leftover state is complete and consistent.
//
// Local source: a directory of per-table *.enc shards (see backupTables.ts), same as
// SFTP / cloud layout, decrypted with the backup phrase — not a raw DB file.
//
// Import order matches BACKUP_RESTORE_ORDER in backupTables.ts (balances overlay, then FK order).
// Every shard file in that list is required. A file that decrypts to zero rows is an empty
// table and is imported, except indexes, which must be exactly one row holding the address
// count and the SCB (or the no-channels marker). A missing file fails the restore.
//
// ECONOMIC INVARIANT: Pending UserInvoicePayment rows (paid_at_unix = 0) are NOT
// restored. Restore favors non-inflation over exact replay. This must be stated
// in code comments and restore-facing documentation.
//
// The SCB travels in the indexes shard, so there is no separate fetch. A shard that marks
// the node as having no channels skips ApplyScb. Otherwise restore fails unless ApplyScb
// succeeds, and a failed SCB leaves the checkpoint at LND_ACTIVE so the same phrase can
// retry. After DB_COMMITTED or LND_ACTIVE, resume is allowed only when the checkpoint
// is complete and consistent (phrase binding, LND still has a wallet, this DB is not
// empty). LND_ACTIVE also requires .restore_wallet_pub from the first PostRestore and
// refuses a different connected wallet. Incomplete or mismatched state is not resumable:
// restore returns a cleanup error instead of continuing. Normal startup must not proceed
// while HasOngoingRecovery() is true (any non-COMPLETED checkpoint file). Recovery
// waiters are notified only after restoreInFlight is cleared.

import { getLogger, PubLogger } from '../helpers/logger.js'
import { deriveBackupKeys, LATEST_DERIVATION_VERSION, type DerivedKeys } from './derivation.js'
import { sftpDownload, cloudSftpConfig, customHostFingerprint, SftpAuthError, type SftpConfig, SFTPFile } from './sftpClient.js'
import crypto from 'crypto'
import fs from 'fs'
import path from 'path'
import Storage from '../storage/index.js'
import * as wizardTypes from '../../../proto/wizard_service/autogenerated/ts/types.js'
import {
    decodeApplicationRow, decodeApplicationUserRow, decodeAdminSettingRow, decodeAppUserDeviceRow,
    decodeUserOfferRow, decodeProductRow, decodeManagementGrantRow, decodeDebitAccessRow,
    decodeInviteTokenRow, decodeBalanceRow, decodeTrackedProviderRow,
    decryptTableRows,
    BackupData,
    decodeIndexesRow,
} from './segments.js'
import { BACKUP_RESTORE_ORDER, backupTableFilename, type BackupTableId } from './backupTables.js'
import SettingsManager from '../main/settingsManager.js'
import { Unlocker } from '../main/unlocker.js'

export const validRestoreSources = ['cloud', 'ftp', 'local'] as const
export type RestoreSource = typeof validRestoreSources[number]

export type RestoreResult = {
    success: boolean
    error?: string
    tablesRestored?: number
}
const CHECKPOINT_FILE = ".restore_checkpoint"
const PHRASE_HASH_FILE = ".restore_phrase_hash"
const WALLET_PUB_FILE = ".restore_wallet_pub"
const ABANDON_RESTORE = 'Delete .restore_checkpoint, .restore_phrase_hash, and .restore_wallet_pub, reset LND and the database, then retry from a clean node.'
const cannotResume = (why: string) => `${why} This restore cannot continue. ${ABANDON_RESTORE}`
enum RestoreCheckpoint {
    STARTED = 'STARTED', // backup fetched and decrypted, phrase bound, about to import DB and init LND
    LND_RECOVERED = 'LND_RECOVERED', // lnd was recovered, but DB not commit, cannot continue recovery from this state
    DB_COMMITTED = 'DB_COMMITTED', // DB committed, any retry will start from after this checkpoint
    LND_ACTIVE = 'LND_ACTIVE', // LND active, SCB can be restored, or retried
    COMPLETED = 'COMPLETED', // SCB restored (or the backup has no channels), restore completed
}

const normalizeRestorePhrase = (phrase: string) =>
    phrase.toLowerCase().trim().replace(/\s+/g, ' ')

export const hashRestorePhrase = (phrase: string) =>
    crypto.createHash('sha256').update(normalizeRestorePhrase(phrase), 'utf8').digest('hex')

const failedRestore = (error: string): wizardTypes.RestoreResponse => ({
    entries_restored: 0,
    scb_restored: false,
    success: false,
    error,
})

export class RestoreManager {
    storage: Storage
    settings: SettingsManager
    log = getLogger({ component: 'restoreManager' })
    unlocker: Unlocker
    private restoreInFlight = false
    private recoveryWaiters: Array<() => void> = []
    constructor(storage: Storage, settings: SettingsManager, unlocker: Unlocker) {
        this.storage = storage
        this.settings = settings
        this.unlocker = unlocker
    }

    getCheckpointPath = () => {
        const dataDir = this.settings.getStorageSettings().dataDir
        return dataDir ? path.join(dataDir, CHECKPOINT_FILE) : CHECKPOINT_FILE
    }

    getPhraseHashPath = () => {
        const dataDir = this.settings.getStorageSettings().dataDir
        return dataDir ? path.join(dataDir, PHRASE_HASH_FILE) : PHRASE_HASH_FILE
    }

    getWalletPubPath = () => {
        const dataDir = this.settings.getStorageSettings().dataDir
        return dataDir ? path.join(dataDir, WALLET_PUB_FILE) : WALLET_PUB_FILE
    }

    updateCheckpoint = (current: RestoreCheckpoint) => {
        fs.writeFileSync(this.getCheckpointPath(), current)
    }
    getCheckpoint = (): RestoreCheckpoint => {
        const checkpointPath = this.getCheckpointPath()
        try {
            const s = fs.readFileSync(checkpointPath, 'utf8').trim()
            if (!s) {
                return RestoreCheckpoint.STARTED
            }
            if (!Object.values(RestoreCheckpoint).includes(s as RestoreCheckpoint)) {
                throw new Error("Invalid checkpoint: " + s)
            }
            return s as RestoreCheckpoint
        } catch (err: any) {
            return RestoreCheckpoint.STARTED
        }

    }

    /** True when a checkpoint file exists and restore has not reached COMPLETED. Includes STARTED. */
    HasOngoingRecovery = (): boolean => {
        const checkpointPath = this.getCheckpointPath()
        if (!fs.existsSync(checkpointPath)) {
            return false
        }
        try {
            const s = fs.readFileSync(checkpointPath, 'utf8').trim()
            if (!s) {
                return true
            }
            return s !== RestoreCheckpoint.COMPLETED
        } catch {
            return true
        }
    }

    IsRecoveryActive = (): boolean => this.restoreInFlight || this.HasOngoingRecovery()

    WaitForRecoveryCompletion = (): Promise<void> => {
        if (!this.IsRecoveryActive()) {
            return Promise.resolve()
        }
        return new Promise(resolve => {
            this.recoveryWaiters.push(resolve)
            // Restore may have left the in-flight/checkpoint window between the check
            // above and registering. Notify here if recovery is already inactive.
            if (!this.IsRecoveryActive()) {
                this.notifyRecoveryComplete()
            }
        })
    }

    private notifyRecoveryComplete = () => {
        const waiters = this.recoveryWaiters
        this.recoveryWaiters = []
        waiters.forEach(w => w())
    }

    hasPhraseBinding = (): boolean => fs.existsSync(this.getPhraseHashPath())

    bindRestorePhrase = (phrase: string) => {
        fs.writeFileSync(this.getPhraseHashPath(), hashRestorePhrase(phrase))
    }

    assertRestorePhraseMatches = (phrase: string) => {
        const hashPath = this.getPhraseHashPath()
        if (!fs.existsSync(hashPath)) {
            throw new Error(cannotResume('The restore checkpoint is missing its phrase binding.'))
        }
        const stored = fs.readFileSync(hashPath, 'utf8').trim()
        if (stored !== hashRestorePhrase(phrase)) {
            throw new Error('Restore phrase does not match the phrase used to start this restore.')
        }
    }

    clearPhraseBinding = () => {
        this.unlinkIfExists(this.getPhraseHashPath())
    }

    bindRestoreWallet = (pub: string) => {
        const normalized = pub.trim().toLowerCase()
        if (!normalized) {
            return
        }
        fs.writeFileSync(this.getWalletPubPath(), normalized)
    }

    getBoundWalletPub = (): string | null => {
        const pubPath = this.getWalletPubPath()
        if (!fs.existsSync(pubPath)) {
            return null
        }
        const stored = fs.readFileSync(pubPath, 'utf8').trim().toLowerCase()
        return stored || null
    }

    clearWalletBinding = () => {
        this.unlinkIfExists(this.getWalletPubPath())
    }

    private unlinkIfExists = (filePath: string) => {
        try {
            fs.unlinkSync(filePath)
        } catch (err: any) {
            if (err.code !== 'ENOENT') throw err
        }
    }

    async RestoreFromSource(req: wizardTypes.RestoreRequest): Promise<wizardTypes.RestoreResponse> {
        if (this.restoreInFlight) {
            return failedRestore('Restore already in progress')
        }
        this.restoreInFlight = true
        try {
            this.log('RestoreFromSource request received', req.source.type)
            return await this.runRestore(req)
        } catch (err: any) {
            this.log('RestoreFromSource failed', err.message || err)
            return failedRestore(err.message || 'restore failed')
        } finally {
            this.restoreInFlight = false
            // COMPLETED (or a no-checkpoint attempt) can still look active while
            // restoreInFlight is true. Wake waiters only after that flag is clear.
            if (!this.HasOngoingRecovery()) {
                this.notifyRecoveryComplete()
            }
        }
    }

    private runRestore = async (req: wizardTypes.RestoreRequest): Promise<wizardTypes.RestoreResponse> => {
        const checkpoint = this.getCheckpoint()
        if (checkpoint === RestoreCheckpoint.COMPLETED) {
            this.log("Restore already completed, returning success")
            return { entries_restored: 0, scb_restored: true, success: true, error: '' }
        }
        const resumable = checkpoint === RestoreCheckpoint.DB_COMMITTED ||
            checkpoint === RestoreCheckpoint.LND_ACTIVE
        const refusal = await this.refusalReason(req, checkpoint, resumable)
        if (refusal) {
            return failedRestore(refusal)
        }
        if (resumable) {
            this.assertRestorePhraseMatches(req.phrase)
        }
        const seed = normalizeRestorePhrase(req.phrase).split(' ')
        const backupData = await this.loadBackup(req)
        const { addressesCount, scb } = backupData.indexes[0]
        this.log("addresses count: " + addressesCount)
        let restoredEntries = 0
        let macaroon: string | undefined
        if (resumable) {
            this.log("LND already recovered and DB already committed, skipping to SCB restore")
        } else {
            const recoveryWindow = Math.max(1000, addressesCount * 10)
            const imported = await this.importAndRecoverLnd(req.phrase, backupData, seed, recoveryWindow)
            restoredEntries = imported.entriesRestored
            macaroon = imported.adminMacaroon
        }
        await this.finishRestore(seed, macaroon, scb)
        return { entries_restored: restoredEntries, scb_restored: !!scb, success: true, error: '' }
    }

    private refusalReason = async (req: wizardTypes.RestoreRequest, checkpoint: RestoreCheckpoint, resumable: boolean): Promise<string | null> => {
        if (checkpoint === RestoreCheckpoint.LND_RECOVERED) {
            return cannotResume('LND has a wallet but the database import did not finish.')
        }
        const walletExists = await this.unlocker.WalletExists()
        const dbClean = await this.storage.IsDbClean()
        const startedInProgress = checkpoint === RestoreCheckpoint.STARTED && this.HasOngoingRecovery()
        if (startedInProgress && walletExists) {
            return cannotResume('Restore stopped before import finished, and LND already has a wallet.')
        }
        if (startedInProgress && !dbClean) {
            return cannotResume('Restore stopped before import finished, and the database is not empty.')
        }
        if (resumable) {
            if (!this.hasPhraseBinding()) {
                return cannotResume('The restore checkpoint is missing its phrase binding.')
            }
            if (!walletExists) {
                return cannotResume('The database was restored, but LND has no wallet.')
            }
            if (dbClean) {
                return cannotResume('The checkpoint says the database was restored, but this database is empty.')
            }
            if (checkpoint === RestoreCheckpoint.LND_ACTIVE && !this.getBoundWalletPub()) {
                return cannotResume('The checkpoint says LND is up, but this restore never recorded which wallet it is.')
            }
        }
        if (!resumable && walletExists) {
            this.log("LND is already started, restore will not continue")
            return 'LND is already started. Restore cannot continue.'
        }
        if (!resumable && !dbClean) {
            return 'Database is not empty. Restore can only run against a freshly initialized database.'
        }
        if (!req.phrase || req.phrase.trim() === '') {
            return 'No phrase provided to restore'
        }
        return null
    }

    private loadBackup = async (req: wizardTypes.RestoreRequest): Promise<BackupData> => {
        this.log("deriving backup keys")
        const keys = await deriveBackupKeys(req.phrase, LATEST_DERIVATION_VERSION)
        const buffers = await this.fetchSegmentsData(req, keys)
        const { backupData } = this.decodeSegmentsData(buffers, keys)
        if (backupData.indexes.length !== 1) {
            throw new Error('indexes shard must contain one address count')
        }
        if (backupData.applications.length === 0) {
            throw new Error('No applications found in backup, cannot restore')
        }
        return backupData
    }

    private importAndRecoverLnd = async (phrase: string, backupData: BackupData, seed: string[], recoveryWindow: number) => {
        this.log("All data needed for restore is available, starting restore process")
        // Bind only now: every earlier failure leaves no checkpoint, so the operator can try another
        // phrase or set the node up fresh. A local folder or FTP login does not prove the phrase,
        // only decryption does.
        this.bindRestorePhrase(phrase)
        this.clearWalletBinding()
        this.updateCheckpoint(RestoreCheckpoint.STARTED)
        const imported = await this.storage.StartTransaction(async tx => {
            this.log("importing dialtone")
            const entriesRestored = await this.importDialtone(backupData, tx)
            this.log("restoring LND wallet")
            const { adminMacaroon } = await this.unlocker.Restore(seed, recoveryWindow)
            this.updateCheckpoint(RestoreCheckpoint.LND_RECOVERED)
            return { entriesRestored, adminMacaroon }
        })
        this.updateCheckpoint(RestoreCheckpoint.DB_COMMITTED)
        return imported
    }

    private finishRestore = async (seed: string[], macaroon: string | undefined, scb: Uint8Array | null) => {
        this.log("waiting LND" + (scb ? " and restoring SCB" : ", backup has no channels"))
        const expectedPub = this.getBoundWalletPub()
        const pub = await this.unlocker.PostRestore(seed, macaroon, expectedPub)
        if (pub && pub !== 'noaction' && !expectedPub) {
            this.bindRestoreWallet(pub)
        }
        this.updateCheckpoint(RestoreCheckpoint.LND_ACTIVE)
        if (scb) {
            await this.restoreScb(Buffer.from(scb))
        } else {
            this.log("backup has no channels, skipping SCB restore")
        }
        this.updateCheckpoint(RestoreCheckpoint.COMPLETED)
        this.clearPhraseBinding()
        this.clearWalletBinding()
        this.log("RestoreFromSource completed")
    }

    async fetchSegmentsData(req: wizardTypes.RestoreRequest, keys: DerivedKeys) {
        this.log("fetching segments data")
        const buffers = new Map<BackupTableId, Buffer>()
        const missing: BackupTableId[] = []
        for (const id of BACKUP_RESTORE_ORDER) {
            const name = backupTableFilename(id)
            const chunk = await fetchFile(this.log, keys, req, name)
            if (!chunk.found) {
                this.log("buffer not found: " + name)
                missing.push(id)
                continue
            }
            buffers.set(id, chunk.data)
        }
        if (missing.length > 0) {
            throw new Error(missing.map(id => failureMessage(req.source.type, id)).join('\n'))
        }
        return buffers
    }

    decodeSegmentsData(buffers: Map<BackupTableId, Buffer>, keys: DerivedKeys) {
        this.log("decoding segments data")
        const readRows = <T>(id: BackupTableId, decodeRow: (u: Uint8Array) => T): T[] => {
            const buffer = buffers.get(id)
            if (!buffer) {
                throw new Error(`missing backup shard ${id}`)
            }
            return decryptTableRows(buffer, keys.encKey).map(decodeRow)
        }

        const backupData: BackupData = {
            indexes: readRows('indexes', decodeIndexesRow),
            balances: readRows('user_balances', decodeBalanceRow),
            trackedProviders: readRows('tracked_providers', decodeTrackedProviderRow),
            applications: readRows('applications', decodeApplicationRow),
            applicationUsers: readRows('application_users', decodeApplicationUserRow),
            adminSettings: readRows('admin_settings', decodeAdminSettingRow),
            appUserDevices: readRows('app_user_devices', decodeAppUserDeviceRow),
            userOffers: readRows('user_offers', decodeUserOfferRow),
            products: readRows('products', decodeProductRow),
            managementGrants: readRows('management_grants', decodeManagementGrantRow),
            debitAccesses: readRows('debit_accesses', decodeDebitAccessRow),
            inviteTokens: readRows('invite_tokens', decodeInviteTokenRow),
        }

        this.log("segments data decrypted, importing dialtone")
        this.log("backupData Data: " + Object.entries(backupData).map(([key, value]) => key + ": " + value.length).join(", "))
        return { backupData }
    }

    async importDialtone(backupData: BackupData, tx: string) {
        let entriesRestored = 0
        const allowPartial = false
        const { balances, trackedProviders, applications,
            applicationUsers, adminSettings, appUserDevices, userOffers,
            products, managementGrants, debitAccesses, inviteTokens } = backupData

        await this.restore("balances", balances.length,
            () => this.storage.userStorage.RestoreBalances(balances, tx), allowPartial)
        entriesRestored += balances.length
        await this.restore("trackedProviders", trackedProviders.length,
            () => this.storage.liquidityStorage.RestoreTrackedProviders(trackedProviders, tx), allowPartial)
        entriesRestored += trackedProviders.length

        await this.restore("applications", applications.length,
            () => this.storage.applicationStorage.RestoreApplications(applications, tx), allowPartial)
        entriesRestored += applications.length
        await this.restore("applicationUsers", applicationUsers.length,
            () => this.storage.applicationStorage.RestoreApplicationUsers(applicationUsers, tx), allowPartial)
        entriesRestored += applicationUsers.length
        await this.restore("adminSettings", adminSettings.length,
            () => this.storage.settingsStorage.RestoreSettings(adminSettings, tx), allowPartial)
        entriesRestored += adminSettings.length
        await this.restore("appUserDevices", appUserDevices.length,
            () => this.storage.applicationStorage.RestoreAppUserDevices(appUserDevices, tx), allowPartial)
        entriesRestored += appUserDevices.length
        await this.restore("userOffers", userOffers.length,
            () => this.storage.offerStorage.RestoreUserOffers(userOffers, tx), allowPartial)
        entriesRestored += userOffers.length
        await this.restore("products", products.length,
            () => this.storage.productStorage.RestoreProducts(products, tx), allowPartial)
        entriesRestored += products.length
        await this.restore("managementGrants", managementGrants.length,
            () => this.storage.managementStorage.RestoreManagementGrants(managementGrants, tx), allowPartial)
        entriesRestored += managementGrants.length
        await this.restore("debitAccesses", debitAccesses.length,
            () => this.storage.debitStorage.RestoreDebitAccesses(debitAccesses, tx), allowPartial)
        entriesRestored += debitAccesses.length
        await this.restore("inviteTokens", inviteTokens.length,
            () => this.storage.applicationStorage.RestoreInviteTokens(inviteTokens, tx), allowPartial)
        entriesRestored += inviteTokens.length
        return entriesRestored
    }

    private restore = async (name: string, length: number, f: () => Promise<number>, allowPartial = false) => {
        const r = await f()
        this.log("restored", r, "of", length, name)
        if (!allowPartial && r !== length) throw new Error("failed to restore all " + name)
    }

    private restoreScb = async (scb: Buffer) => {
        this.log("restoring SCB")
        try {
            await this.unlocker.ApplyScb(scb)
        } catch (err: any) {
            this.log("Failed to restore SCB will retry once: " + (err.message || err))
            await this.unlocker.ApplyScb(scb)
        }
    }

}

const fetchFile = async (log: PubLogger, keys: DerivedKeys, opts: wizardTypes.RestoreRequest, filename: string): Promise<SFTPFile> => {
    log("fetching file: " + filename, "source: " + opts.source.type)
    switch (opts.source.type) {
        case wizardTypes.RestoreRequest_source_type.CLOUD:
            return downloadFromCloud(keys, filename)
        case wizardTypes.RestoreRequest_source_type.FTP_HOST:
            if (!opts.source.ftp_host) throw new Error('--ftp-host is required for source=ftp')
            const sftpConf: SftpConfig = {
                host: opts.source.ftp_host,
                username: opts.creds_override?.user ?? keys.sftpUser,
                password: opts.creds_override?.pass ?? keys.sftpPass,
                hostFingerprint: customHostFingerprint(opts.source.ftp_host, 22, ''),
            }
            return sftpDownload(sftpConf, filename)

        case wizardTypes.RestoreRequest_source_type.LOCAL_PATH: {
            const dir = opts.source.local_path
            if (!dir) throw new Error('Local path is required for source=local')
            if (!fs.existsSync(dir)) {
                return { found: false }
            }
            const stat = fs.statSync(dir)
            if (!stat.isDirectory()) {
                return { found: false }
            }
            const filePath = path.join(dir, filename)
            if (!fs.existsSync(filePath) || !fs.statSync(filePath).isFile()) {
                return { found: false }
            }
            return { found: true, data: fs.readFileSync(filePath) }
        }

        default:
            throw new Error(`Unknown restore source: ${opts.source}`)
    }
}

/**
 * Login rejected while restoring from the managed cloud.
 * Distinct from a missing shard: the server refused the seed's account.
 */
export class CloudLoginRejectedError extends Error {
    constructor(loginError: string) {
        super(`Cloud backup login rejected: ${loginError}. This seed has no cloud account, or the server refused the password.`)
        this.name = 'CloudLoginRejectedError'
    }
}

/** Map a cloud download failure onto a restore error. Auth rejection is not a missing file. */
export function cloudDownloadError(err: unknown): Error {
    if (err instanceof SftpAuthError) return new CloudLoginRejectedError(err.message)
    if (err instanceof Error) return err
    return new Error(`Cloud backup download failed: ${String(err)}`)
}

const downloadFromCloud = async (keys: DerivedKeys, filename: string): Promise<SFTPFile> => {
    try {
        return await sftpDownload(cloudSftpConfig(keys.sftpUser, keys.sftpPass), filename)
    } catch (err) {
        throw cloudDownloadError(err)
    }
}

export function failureMessage(source: wizardTypes.RestoreRequest_source_type, shard: BackupTableId): string {
    const name = backupTableFilename(shard)
    switch (source) {
        case wizardTypes.RestoreRequest_source_type.CLOUD:
            return `No backup found for this seed on the managed service (missing ${name}). The login succeeded; this shard is not there.`
        case wizardTypes.RestoreRequest_source_type.FTP_HOST:
            return `No backup file ${name} on the SFTP server. The connection succeeded; verify this account has a backup.`
        case wizardTypes.RestoreRequest_source_type.LOCAL_PATH:
            return `${name} not found or path is not a readable directory — expected a folder of per-table *.enc shards from backup.`
        default: {
            const _exhaustive: never = source
            throw new Error(`Unknown restore source: ${_exhaustive}`)
        }
    }
}


export const parseRestoreFlags = (flags: Record<string, string>): wizardTypes.RestoreRequest => {
    const phrase = flags['phrase']
    if (!phrase) {
        throw new Error('Error: --phrase is required')
    }
    const source = flags['source'] as RestoreSource
    if (!source) {
        throw new Error('Error: --source is required (cloud|ftp|local)')
    }

    if (!validRestoreSources.includes(source)) {
        throw new Error(`Error: --source must be one of: ${validRestoreSources.join(', ')}`)
    }
    const credsOverr = !!flags['ftp-user'] && !!flags['ftp-pass']
    const creds: wizardTypes.FtpCreds | undefined = credsOverr ? {
        user: flags['ftp-user'],
        pass: flags['ftp-pass'],
    } : undefined

    if (source === 'ftp') {
        const sftpHost = flags['ftp-host']
        if (!sftpHost) {
            throw new Error('Error: --ftp-host is required when source=ftp')
        }
        return {
            phrase, source: {
                type: wizardTypes.RestoreRequest_source_type.FTP_HOST,
                ftp_host: sftpHost,
            }, creds_override: creds,
        }
    } else if (source === 'local') {
        const localPath = flags['local-path']
        if (!localPath) {
            throw new Error('Error: --local-path is required when source=local')
        }
        return {
            phrase, source: {
                type: wizardTypes.RestoreRequest_source_type.LOCAL_PATH,
                local_path: localPath,
            }, creds_override: creds,
        }
    } else {
        return {
            phrase, source: {
                type: wizardTypes.RestoreRequest_source_type.CLOUD,
                cloud: {}
            }, creds_override: creds,
        }
    }
}