version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bitcore-lib
    versions:
    - 8.24.2
    - 8.25.0
    - 8.25.2
    - 8.25.3
    - 8.25.4
    - 8.25.7
    - 9.0.0
  - dependency-name: socket.io
    versions:
    - 3.1.0
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
