import { nip44 } from "nostr-tools"
import * as Types from "../../../proto/autogenerated/ts/types.js"
import { PushPair, ShockPush, ShockPushNotification } from "../ShockPush/index.js"
import { ERROR, getLogger, PubLogger } from "../helpers/logger.js"
import { Application } from "../storage/entity/Application.js"
import { ApplicationUser } from "../storage/entity/ApplicationUser.js"
import Storage from "../storage/index.js"
import SettingsManager from "./settingsManager.js"

export class NotificationsManager {
    private settings: SettingsManager
    private storage: Storage
    private clients: Record<string, ShockPush> = {}
    private logger: PubLogger
    constructor(settings: SettingsManager, storage: Storage) {
        this.settings = settings
        this.storage = storage
        this.logger = getLogger({ component: 'notificationsManager' })
    }

    private getClient = (pair: PushPair) => {
        const client = this.clients[pair.pubkey]
        if (client) {
            return client
        }
        const newClient = new ShockPush(this.settings.getSettings().serviceSettings.shockPushBaseUrl, pair)
        this.clients[pair.pubkey] = newClient
        return newClient
    }

    SendNotification = async (notification: ShockPushNotification, messagingTokens: string[], pair: PushPair) => {
        if (!this.settings.getSettings().serviceSettings.shockPushBaseUrl) {
            this.logger("ShockPush is not configured, skipping notification")
            return
        }
        try {
            const client = this.getClient(pair)
            await client.SendNotification(notification, messagingTokens)
        } catch (err: any) {
            this.logger(ERROR, "failed to send push notification", err.message || err)
        }
    }

    SendEncryptedPayload = async (app: Application, appUser: ApplicationUser, payload: Types.PushNotificationPayload, { title, body }: { title: string, body: string }) => {
        try {
            if (!appUser.nostr_public_key) {
                return
            }
            const devices = await this.storage.applicationStorage.GetAppUserDevices(appUser.identifier)
            if (devices.length === 0) {
                return
            }
            const tokens = devices.map(d => d.firebase_messaging_token)
            const ck = nip44.getConversationKey(Buffer.from(app.nostr_private_key!, 'hex'), appUser.nostr_public_key)
            const envelope: Types.PushNotificationEnvelope = {
                topic_id: appUser.topic_id,
                app_npub_hex: app.nostr_public_key!,
                encrypted_payload: nip44.encrypt(JSON.stringify(payload), ck)
            }
            await this.SendNotification({
                message: JSON.stringify(envelope),
                body,
                title
            }, tokens, {
                pubkey: app.nostr_public_key!,
                privateKey: app.nostr_private_key!
            })
        } catch (err: any) {
            this.logger(ERROR, "failed to send encrypted push notification", err.message || err)
        }
    }
}
