// This file was autogenerated from a .proto file, DO NOT EDIT!

package lightning_pub

type ResultError struct {
	Status string `json:"status"`
	Reason string `json:"reason"`
}
type GuestContext struct {
}
type LndState string

const (
	OFFLINE LndState = "OFFLINE"
	ONLINE  LndState = "ONLINE"
	SYNCING LndState = "SYNCING"
)

type AdminConnectInfoResponse struct {
	Connect_info *AdminConnectInfoResponse_connect_info `json:"connect_info"`
	Nprofile     string                                 `json:"nprofile"`
}
type ConfigRequest struct {
	Automate_liquidity    bool   `json:"automate_liquidity"`
	Avatar_url            string `json:"avatar_url"`
	Push_backups_to_nostr bool   `json:"push_backups_to_nostr"`
	Relay_url             string `json:"relay_url"`
	Source_name           string `json:"source_name"`
}
type Empty struct {
}
type ServiceStateResponse struct {
	Admin_npub            string   `json:"admin_npub"`
	App_id                string   `json:"app_id"`
	Automate_liquidity    bool     `json:"automate_liquidity"`
	Avatar_url            string   `json:"avatar_url"`
	Http_url              string   `json:"http_url"`
	Lnd_state             LndState `json:"lnd_state"`
	Nprofile              string   `json:"nprofile"`
	Provider_name         string   `json:"provider_name"`
	Push_backups_to_nostr bool     `json:"push_backups_to_nostr"`
	Relay_connected       bool     `json:"relay_connected"`
	Relay_url             string   `json:"relay_url"`
	Relays                []string `json:"relays"`
	Source_name           string   `json:"source_name"`
	Watchdog_ok           bool     `json:"watchdog_ok"`
}
type StateResponse struct {
	Admin_linked bool `json:"admin_linked"`
	Config_sent  bool `json:"config_sent"`
}
type AdminConnectInfoResponse_connect_info_type string

const (
	ADMIN_TOKEN   AdminConnectInfoResponse_connect_info_type = "admin_token"
	ENROLLED_NPUB AdminConnectInfoResponse_connect_info_type = "enrolled_npub"
)

type AdminConnectInfoResponse_connect_info struct {
	Type          AdminConnectInfoResponse_connect_info_type `json:"type"`
	Admin_token   *string                                    `json:"admin_token"`
	Enrolled_npub *string                                    `json:"enrolled_npub"`
}
